[package]
name = "slintui_preview"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/slintui_preview.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
